### ISSUE TITLE
Commandline tool

### ISSUE THREAD

**Issue by dmadisetti** [craedl/craedl-sdk-python#4]
I wrote a small script for my use case in late November. It looks like you guys are are still under pretty active development, and my code is starting to diverge from yours quiet a bit.

You can see my changes here:

https://github.com/craedl/craedl-sdk-python/compare/master...AnotherGroupChat:cli-tool

vs here

https://github.com/AnotherGroupChat/craedl-sdk-python/compare/cli-tool...craedl:master

Notable differences from current master:
 - I implemented my own recursive upload
 - I don't have any of the logging stuff you guys put in
 - I don't have the retry stuff (your current implementation might be better done using a decorator?)
 - I use a yaml config, and click over just reading a text file

Spec of the tool. Currently a bit of a hack, but the idea is you can do

```craedl <local-path> <craedl-project>:<craedl-path>```

Which uploads local-path to the given project and location

 and 

```craedl <craedl-project>:<craedl-path>@<version> <local-path>```

Which downloads a given version from a given project and path to a local location. If no project is specified, the current is used.

---

Anyway, let me know if this is something on your roadmap, or I might revisit it once everything is a bit more stable.

Thanks!

**Comment by ajsierakowski** [comment]
Yes, we are indeed still in heavy development, which is why the SDK remains in a pre-release state. A CLI is on the roadmap, but relatively low priority at this time.
