### ISSUE TITLE
Quickly bulk upload many files?

### ISSUE THREAD

**Issue by dmadisetti** [craedl/craedl-sdk-python#5]
I was attempting to use craedl for a large number of file uploads (a few hundred), but this seems pretty slow compared to uploading say a zip.

Might there be a way to allow for zip uploads which can then be unpacked? Individual requests are quiet slow. GLOBUS also has an API which may help with speed https://globus-sdk-python.readthedocs.io/en/stable/

**Comment by ajsierakowski** [comment]
This is because of the network latency involved each file upload. We are working to improve this to the extent that we can. We do not currently have support for unpacking zip uploads or supporting Globus transfers on our roadmap.
